version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DBPASSWORD
      POSTGRES_USER: $DBUSER
      POSTGRES_DB: $DBNAME
    ports:
      - 15432:5432
    volumes:
      - ./conf/db/init:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - 80:80
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: $DBUSER 
      DATABASE_NAME: $DBNAME
      DATABASE_PASSWORD: $DBPASSWORD
      SECRET_KEY: $SECRET_KEY
    depends_on:
      - db
    volumes:
      - .:/app
    tty: true
    stdin_open: true
